# Generated by Django 6.1 on 2026-08-25 03:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Glassware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MeasurementUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('label', models.CharField(max_length=60)),
                ('kind', models.CharField(choices=[('volume', 'Volume'), ('weight', 'Weight'), ('count', 'Count'), ('qualitative', 'Qualitative')], max_length=20)),
            ],
            options={
                'ordering': ('kind', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('slug', models.SlugField(max_length=90, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['is_active', 'name'], name='catalog_equ_is_acti_f6e3e4_idx')],
            },
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('short_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('curated_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('primary_image', models.ImageField(blank=True, upload_to='cocktails/')),
                ('primary_glassware', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_cocktails', to='catalog.glassware')),
                ('tags', models.ManyToManyField(blank=True, related_name='cocktails', to='catalog.tag')),
            ],
            options={
                'ordering': ('curated_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='IngredientCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=110, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ('display_order', 'name'),
                'indexes': [models.Index(fields=['display_order', 'name'], name='catalog_ing_display_08f81f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_image', models.ImageField(blank=True, upload_to='ingredients/')),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredients', to='catalog.ingredientcategory')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CocktailIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('role', models.CharField(choices=[('ingredient', 'Ingredient'), ('garnish', 'Garnish'), ('ice', 'Ice')], default='ingredient', max_length=12)),
                ('preparation_note', models.CharField(blank=True, max_length=255)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_ingredients', to='catalog.cocktail')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cocktail_uses', to='catalog.ingredient')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recipe_ingredients', to='catalog.measurementunit')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='PreparationStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('instruction', models.TextField()),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_steps', to='catalog.cocktail')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='CocktailEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('cocktail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_items', to='catalog.cocktail')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cocktail_uses', to='catalog.equipment')),
            ],
            options={
                'ordering': ('sort_order', 'pk'),
                'indexes': [models.Index(fields=['cocktail', 'sort_order'], name='catalog_coc_cocktai_136eb4_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['is_active', 'name'], name='catalog_ing_is_acti_d6f476_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['category', 'name'], name='catalog_ing_categor_fba6d5_idx'),
        ),
        migrations.AddIndex(
            model_name='cocktailingredient',
            index=models.Index(fields=['cocktail', 'sort_order'], name='catalog_coc_cocktai_ca1d66_idx'),
        ),
        migrations.AddIndex(
            model_name='cocktailingredient',
            index=models.Index(fields=['ingredient', 'cocktail'], name='catalog_coc_ingredi_ba2cee_idx'),
        ),
        migrations.AddConstraint(
            model_name='preparationstep',
            constraint=models.UniqueConstraint(fields=('cocktail', 'sort_order'), name='unique_preparation_step_order'),
        ),
        migrations.AddIndex(
            model_name='cocktail',
            index=models.Index(fields=['status', 'curated_order', 'name'], name='catalog_coc_status_e14d22_idx'),
        ),
    ]
